export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOADING_DETAIL_PRODUCT = "LOADING_DETAIL_PRODUCT";
export const LOAD_DETAIL_PRODUCT = "LOAD_DETAIL_PRODUCT";

export const ADD_PRODUCTS = "ADD_PRODUCTS";

export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const FETCH_TRANSACTION = "FETCH_TRANSACTION";
export const LOADING_TRANSACTION = "LOADING_TRANSACTION"
// export const ADD_PRODUCTS = "ADD_PRODUCTS";
// export const LOAD_PRODUCTS = "LOAD_PRODUCTS"

// export const LOADING_HISTORY = "LOADING_HISTORY"
// export const LOAD_HISTORY = "LOAD_HISTORY"
// export const DELETE_HISTORY = "DELETE_HISTORY"
