
export const LOADING_PRODUCTS = "LOADING_PRODUCTS"
export const LOAD_PRODUCTS = "LOAD_PRODUCTS"
export const LOADING_DETAIL_PRODUCT = "LOADING_DETAIL_PRODUCT"
export const LOAD_DETAIL_PRODUCT = "LOAD_DETAIL_PRODUCT"

// export const LOADING_HISTORY = "LOADING_HISTORY"
// export const LOAD_HISTORY = "LOAD_HISTORY"
// export const DELETE_HISTORY = "DELETE_HISTORY"
